import{a as l}from"./assets/vendor-ngrFHoWO.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const c of t.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const i="https://gnews.io/api/v4/search",u="7b3b1b68eaf0145324516cf2b6d07dde";async function m(o){const r={apikey:u,q:o,max:5,lang:"ru"};try{return await l.get(i,{params:r})}catch(s){throw console.error("Ошибка при получении данных от сервера"),s}}function g(){const o={apikey:u,q:"Bitcoin",max:5,lang:"ru"};return l.get(i,{params:o}).then(r=>console.log(r.data.articles)).catch(r=>{console.log(r.message)})}const f=document.querySelector(".gallery"),a=document.querySelector(".form"),y=document.querySelector(".input-form");function h(){f.innerHTML=""}async function p(){try{a.addEventListener("submit",async o=>{o.preventDefault();const r=y.value.trim(),n=(await m(r)).data.articles;h(),b(n),console.log(r),r===""?console.log("Error"):p()})}catch(o){console.error(o.message)}finally{a.reset()}}function b(o){const r=o.map(({title:s,description:n,publishedAt:e,url:t,source:c,image:d})=>` 
                <li class="gallery-item">
                    <img src="${d}" class="gallery-img">
                    <h2 class="gallery-title">${s}</h2>
                    <p class="gallery-description">${n}</p>
                    <p class="gallery-publichedAt">Опубликовано: ${e}</p>
                    <a class="gallery-link" href="${t}">${c.name}</a>
                </li>
            `).join("");f.insertAdjacentHTML("beforeend",r)}p();g();
//# sourceMappingURL=index.js.map
